### ISSUE TITLE
Refactor the distro layer to handle different distros in bash scripts

### ISSUE THREAD

**Issue by lizzha** [LIS/LISAv2#122]
Now in multiple test scripts, it detects the distro name and version. We can extract the code dealing with distros in a common utils, so that test scripts do not need to handle different distros

**Comment by chvalean** [comment]
@lizzha this is being done in utils.sh by the GetDistro function [here - link](https://github.com/LIS/LISAv2/blob/master/Testscripts/Linux/utils.sh#L236) 
Please close this issue if that is fine, or update the issue description to what changes maybe have to be done to that function to extend it?
Thank you!

**Comment by lizzha** [comment]
This is done, by refactoring the performance test code
