### ISSUE TITLE
Logs collection error due to mismatched hostnames

### ISSUE THREAD

**Issue by iamshital** [LIS/LISAv2#129]
Recently I'm seeing an issue with downloading log files from VM before cleaning up.

**Logs.**
[Azure VERIFY-DEPLOYMENT-PROVISION westus2] 08/02/2018 07:48:35 : [INFO ] Downloading ICA-RG-SingleVM-microsoft-ONTV-636687925779-role-0-*.txt from lisa : 13.77.143.39,port 22 to .\TestResults\2018-02-08-07-42-44-9392\VERIFY-DEPLOYMENT-PROVISION using Password authentication
[Azure VERIFY-DEPLOYMENT-PROVISION westus2] .
[Azure VERIFY-DEPLOYMENT-PROVISION westus2] 08/02/2018 07:48:36 : [INFO ] Download command returned exit code 1
[Azure VERIFY-DEPLOYMENT-PROVISION westus2] 08/02/2018 07:48:36 : [INFO ] .\tools\pscp.exe : Looking up host "13.77.143.39" At line:11 char:17 + ...    echo y | .\tools\pscp.exe  -v -2 -unsafe -pw $password -q -P $port ... +                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~     + CategoryInfo          : NotSpecified: (Looking up host "13.77.143.39":St     ring) [], RemoteException     + FullyQualifiedErrorId : NativeCommandError   Connecting to 13.77.143.39 port 22  We claim version: SSH-2.0-PuTTY_Release_0.63  Server version: SSH-2.0-OpenSSH_7.4  Using SSH protocol version 2  Using Diffie-Hellman with standard group "group14"  Doing Diffie-Hellman key exchange with hash SHA-1  Host key fingerprint is:  ssh-rsa 2048 ae:d9:4f:4e:05:8c:f3:07:de:4e:3d:01:50:de:fa:f3  Initialised AES-256 SDCTR client->server encryption  Initialised HMAC-SHA-256 client->server MAC algorithm  Initialised AES-256 SDCTR server->client encryption  Initialised HMAC-SHA-256 server->client MAC algorithm  Using username "lisa". Using SSPI from SECUR32.DLL  Attempting GSSAPI authentication  GSSAPI authentication request refused  Attempting keyboard-interactive authentication  Access granted  Opening session as main channel  Opened main channel  Started a shell/command  Using SFTP Connected to 13.77.143.39 pscp: wildcard 'ICA-RG-SingleVM-microsoft-ONTV-636687925779-role-0-*.txt'  matched no files Sent EOF message  Server sent command exit status 0  Disconnected: All channels closed  DownloadExtiCode_1

**Distro**
CentOS 7.5
Other distros are not verified yet.

**Comment by chvalean** [comment]
@asofron please do a rerun of this on centos 7.5 with latest lisav2 code and see if it still repro.

**Comment by asofron** [comment]
Created issue  [#1413](https://github.com/Azure/WALinuxAgent/issues/1413) for WaLinuxAgent with relevant information

**Comment by iamshital** [comment]
WALA issue is still open.

**Comment by asofron** [comment]
@iamshital  I`ll re-test to check if there any change , as well

**Comment by lizzha** [comment]
Issue is fixed
