### ISSUE TITLE
SRIOV tests fail because of a breaking change in the test framework

### ISSUE THREAD

**Issue by ader1990** [LIS/LISAv2#137]
Because of this commit: https://github.com/LIS/LISAv2/commit/b00d5b54d202bcc6904cc41de7fbc745780a6c67#diff-fd8a417b18cc4776c967999f5ef81c74

the state file of the linux test cases is /home/lisa/state.txt and not /home/lisa/TestState.log, thus breaking all the automation relying on that.

TC needed to be fixed:
Functional_NICS_SRIOV_IFUP

@iamshital do you have other TCs affected?

**Comment by ader1990** [comment]
@iamshital @juhlee-microsoft we need to define and document an exact workflow of test case (error) logging and status via text files, which each test should respect.
There is no documentation on this matter, so we cannot enforce anything for the test case developer and maintainer.

**Comment by iamshital** [comment]
@ader1990 , Yes. I've noticed the breaking change and some of the tests are broke. I'm fixing them one by one. (5/6 tests affected)

**Comment by ader1990** [comment]
SRIOV tests are fixed, closing this issue.
