### ISSUE TITLE
Revise utils files

### ISSUE THREAD

**Issue by lizzha** [LIS/LISAv2#154]
This common_utils.sh and utils.sh have many similar methods with duplicated functionalities, we need to identify the methods one by one, and create merge them together

**Comment by lizzha** [comment]
And need to add necessary description for functions in utils files

**Comment by lizzha** [comment]
Now I've put contents in common_utils.sh (previous azuremodules.sh) to utils.sh, need revise later

**Comment by chvalean** [comment]
Resolved by merging all functions into utils.sh.
