### ISSUE TITLE
VMGroup not cleaned up on Hyper-V

### ISSUE THREAD

**Issue by adriansuhov** [LIS/LISAv2#182]
When running Get-VMGroup on a host where lisav2 was run, I discovered that I had 100+ vm groups from previous lisav2 runs. Even though VMs are cleaned ok, VM groups aren't.

PS C:\Users\v-adsuho\Documents\lisav2> get-vmgroup | fl name | wc -l
266

**Comment by chvalean** [comment]
@iamshital do you have some bandwidth to work on this maybe?

**Comment by iamshital** [comment]
No Chris.. Given the current P0 items in our plate, Please assign this to someone in your team.

**Comment by chvalean** [comment]
Assigning to @ader1990 to implement.

**Comment by chvalean** [comment]
Fix in PR #241
