### ISSUE TITLE
Tests backport - 3rd sprint

### ISSUE THREAD

**Issue by chvalean** [LIS/LISAv2#183]
- [x] Core LIS - 5 tests @asofron 
- [x] Time sync - 7 tests @adriansuhov 
- [x] kdump - 7 tests @mbivolan 
- [ ] Network - 26 tests @adriansuhov 
- [x] Vmbus and NMI - 5 tests @ader1990 
- [ ] Stress - 5 tests @mbivolan

**Comment by ader1990** [comment]
We should have the PRs addressing these issues, something like gerrit review approach:
in the commit message to have Implements | Partially implements | Fixes (Issue issue link)

**Comment by juhlee-microsoft** [comment]
@chvalean I think this is internal communication topic. Can we close this and work internal communication tool like VSTS? If agree, please close.
