### ISSUE TITLE
CommonFunctions.psm1: switch from plink to RunLinuxCmd

### ISSUE THREAD

**Issue by chvalean** [LIS/LISAv2#186]
plink.exe is used too many times in the module, we could switch to RunLinuxCmd function to have a common model.
Must remove then Send-CommandToVM and rely only on RunLinuxCmd

**Comment by iamshital** [comment]
@chvalean Thanks for this.

**Comment by juhlee-microsoft** [comment]
There are still many places calling plink in KVP and FCOPY test scripts. Please replace with RunLinuxCmd call.
