### ISSUE TITLE
Test and assign correct ulimit values in NTTTCP tests

### ISSUE THREAD

**Issue by iamshital** [LIS/LISAv2#219]

**Comment by chvalean** [comment]
@iamshital can you please add the details to this issue and what needs to be done?
If this item is too old, please close it, or start an internal thread to discuss.
Thank you!

**Comment by iamshital** [comment]
@chvalean It was about setting ulimit value to 204800 before running the ntttcp tests. It is already part of LISAv2 now. Closing.
