### ISSUE TITLE
DoTestCleanUp fails if the VM is not in running state

### ISSUE THREAD

**Issue by ader1990** [LIS/LISAv2#220]
DoTestCleanUp expects the vm to be running, but the test case might leave the vm in another state on purpose or it can just fail.
If this method: DoTestCleanUp is run, the vms should be put on running state (or at least try to set them on running state).

Here is the problem:
https://github.com/LIS/LISAv2/blob/a6755bf517d52c1f869db4af24c8757cb9501db4/Libraries/Test-Framework.psm1#L530

The same workflow should be followed:
https://github.com/LIS/LISAv2/blob/a6755bf517d52c1f869db4af24c8757cb9501db4/Libraries/Test-Framework.psm1#L534

**Comment by juhlee-microsoft** [comment]
Internally recorded.
