### ISSUE TITLE
Improve checking of the call traces

### ISSUE THREAD

**Issue by iamshital** [LIS/LISAv2#26]
Current method: `dmesg | grep -i 'call trace'`
Proposed method : `grep -rnw '/var/log' -e 'call trace' --ignore-case`
Reason: I've seen that if the dmesg is reset then call traces appeared earlier, will not show in output of "dmesg" command.

**Comment by chvalean** [comment]
@juhlee-microsoft  re-assigning this request to Andrei to cover at some point this month.
