### ISSUE TITLE
Expand-XMLVirtualMachineSet throw out exception

### ISSUE THREAD

**Issue by LiliDeng** [LIS/LISAv2#262]
@iamshital Hi, I run test cases, hit exception in method Expand-XMLVirtualMachineSet, I have no VirtualMachineSet in setupType.

**Comment by LiliDeng** [comment]
+ @juhlee-microsoft to address this issue.

**Comment by santoshx** [comment]
I posted a possible guess work fix in PR #266

**Comment by adriansuhov** [comment]
This has been reverted: https://github.com/LIS/LISAv2/pull/267

**Comment by iamshital** [comment]
ACK

**Comment by LiliDeng** [comment]
Issue resolved
