### ISSUE TITLE
Latest code fails for me on Windows10/HyperV :  Exception in Expand-XMLVirtualMachineSet.

### ISSUE THREAD

**Issue by santoshx** [LIS/LISAv2#265]
10/10/2018 09:47:07 : [ERROR] Exception in Expand-XMLVirtualMachineSet.
10/10/2018 09:47:07 : [OOPS   ]: You cannot call a method on a null-valued expression.
10/10/2018 09:47:07 : [SOURCE ]: Line 1098 in script .\Libraries\Framework.psm1.
10/10/2018 09:47:07 : [INFO ] EXCEPTION : Calling function - ThrowException
10/10/2018 09:47:07 : [INFO ] Source : Line 42 in script .\Libraries\CommonFunctions.psm1.
10/10/2018 09:47:07 : [INFO ] LISAv2 exits with code: 1

This is quick announce. 
I've not tried to debug it.

**Comment by adriansuhov** [comment]
Failing on my Hyper-V env too

**Comment by santoshx** [comment]
Duplicate of #262
