### ISSUE TITLE
azure: Adding dependency packets before running the tests

### ISSUE THREAD

**Issue by adriansuhov** [LIS/LISAv2#301]
Currently the automation doesn't check & add dependency packets for most of the tests. Some examples:

- BVT tests - if "python" is missing, all the tests will fail
- VERIFY-SRIOV-LSPCI - if "pciutils" packet is missing the test will fail
- VERIFY-IFUP-IFDOW-ETH0-RMMOD-MODPROBE-HV_NETVSC-SRIOV - if "ifupdown" packet is missing the test will fail
- Performance tests have package dependencies that are not installed/covered on all distros.

And the list goes on, these are only a few examples that I encountered during testing.
A check for packets should be performed before the actual test is run and the missing ones should be installed. This can be performed on each test or on each test area. 
Or an option for custom packets at run time should be added (same as custom vhd or custom kernel).

**Comment by chvalean** [comment]
@juhlee-microsoft @iamshital we should setup a call to review the original Azure BVT tests.

**Comment by juhlee-microsoft** [comment]
@adriansuhov @chvalean  please review this issue and close it if this is no longer applicable.

**Comment by chvalean** [comment]
VERIFY-SRIOV-LSPCI - backend function VerifyVF handles now the pciutils package installation.

Closing this issue, will track other missing dependencies and other tests have been improved in the meantime.
