### ISSUE TITLE
custom kernel install should fail if it does not install a custom kernel

### ISSUE THREAD

**Issue by ader1990** [LIS/LISAv2#309]
This code should not be here, as it contradicts the logic of customKernelInstall, because the code path continues even when a kernel is not installed.

https://github.com/LIS/LISAv2/blob/8de80f2f8a9528f43e1da2a9824a7279c2cc3b72/Libraries/CommonFunctions.psm1#L407

@iamshital what is the purpose of "installing a new kernel", but continue even when failing to install a new kernel?

**Comment by chvalean** [comment]
@iamshital That might be true for "latest" in a short window of time, but ppa/proposed cannot be present in an Azure image to be considered as already present.

Let's restrict this only to "latest" option quickly and close this - @ader1990

**Comment by chvalean** [comment]
Closing this, will revise if needed at a later time.
