### ISSUE TITLE
Possible bug in check_exit_status function in utils.sh

### ISSUE THREAD

**Issue by prashantmhetar** [LIS/LISAv2#314]
This function should update the  test state while exiting and also update the summary in error case.

function check_exit_status ()
{
        exit_status=$?
        message=$1

        cmd="echo"
        if [ ! -z $2 ]; then
                cmd=$2
        fi

        if [ $exit_status -ne 0 ]; then
                $cmd "$message: Failed (exit code: $exit_status)"
                if [ "$2" == "exit" ]; then
                        exit $exit_status
                fi
        else
                $cmd "$message: Success"
        fi
}

**Comment by lizzha** [comment]
this function is only to check the command exit status. If you want to update test summary, you can pass the function name UpdateSummary as the second parameter

**Comment by prashantmhetar** [comment]
We can modify the code as below. As this function is part of utils.sh it can invoke UpdateSummary and SetTestStateAborted depends on the exit_status.
function check_exit_status ()
{
        exit_status=$?
        message=$1

        cmd="echo"
        if [ ! -z $2 ]; then
                cmd=$2
        fi

        if [ $exit_status -ne 0 ]; then
                $cmd "$message: Failed (exit code: $exit_status)"
                UpdateSummary "$message Failed·(exit·code:·$exit_status)"
                if [ "$2" == "exit" ]; then
                        SetTestStateAborted
                        exit $exit_status
                fi
        else
                $cmd "$message: Success"
                UpdateSummary "$message: Success"
        fi
}

**Comment by prashantmhetar** [comment]
Added this change as part of https://github.com/LIS/LISAv2/pull/307 review

**Comment by prashantmhetar** [comment]
Closing this issue as modified change in merged
