### ISSUE TITLE
Possible issue in Parse-TestParameters 

### ISSUE THREAD

**Issue by sireeshapotnuru** [LIS/LISAv2#321]
In XML if we have multiple param with the same name, previous value is overwritten and considered only last value
For Example: 
if we have testparams as below, only value "IDE=0,1,Dynamic" is taken
`<TestParameters>
    <param>IDE=1,1,Dynamic</param>
    <param>IDE=0,1,Dynamic</param>
</TestParameters>`

Output Log:
10/26/2018 10:31:08 : [INFO ] Test setup/cleanup started using script:.\TestScripts\Windows\AddHardDisk.ps1 with parameters:IDE=0,1,Dynamic;
10/26/2018 10:31:08 : [INFO ] New-HardDrive ICA-HG-SingleVM-sireesha-MTQE-636761662652-role-0 localhost False 0 1 Dynamic
10/26/2018 10:31:08 : [INFO ] Enter New-HardDrive ICA-HG-SingleVM-sireesha-MTQE-636761662652-role-0 localhost False 0 1 Dynamic
10/26/2018 10:31:09 : [INFO ] Success

function Parse-TestParameters {
    <#
    .DESCRIPTION
    Converts the parameters specified in the test definition into a hashtable
    to be used later in test.
    #>

    param(
        $XMLParams,
        $XMLConfig
    )

    $testParams = @{}
    foreach ($param in $XMLParams.param) {
        $name = $param.split("=")[0]
        if ($name -eq "SECRET_PARAMS") {
            $paramsArray = $param.split("=")[1].trim("(",")"," ").split(" ")
            $testParams += Get-SecretParams -ParamsArray $paramsArray `
                 -XMLConfig $XMLConfig
        } else {
            $value = $param.split("=")[1]
            $testParams[$name] = $value // Overwriting value here
        }
    }

    return $testParams
}

**Comment by adriansuhov** [comment]
This is by design because $testParams is a hashtable that contains key/value pairs & there cannot be keys with the same values. 
If you want multiple similar parameters, just use PARAM_1, PARAM_2 (e.g. on some NET tests I used NIC_1 and NIC_2 as parameters).
Keep in mind that **it's not a good practice** to have parameters with the same name.
If you have any questions, please let me know. If not, you can close the issue

**Comment by santoshx** [comment]
In lis-test there are params with same name repeated hence the question arise.
However, as suggested we'll not use same names here in lisav2

**Comment by sireeshapotnuru** [comment]
We reopened this issue, as per Chris comment

1.	STOR-VSS-BACKUPRESTORE-MULTIFS-VHDX 
We have raised issue https://github.com/LIS/LISAv2/issues/321 as having same input parameters overwritten. 
As suggested to have param as NAME_1, NAME_2, it needs change in AddVhdxHardDisk.ps1 which could impact other tests. Please suggest.
**Chris Comment** - Adrian posted a comment to that, let’s continue the discussion there. Haven’t had time to think about a solution to this.

**Comment by prashantmhetar** [comment]
PR is created with modifying AddVhdxHardDisk.ps1
https://github.com/LIS/LISAv2/pull/376

**Comment by sireeshapotnuru** [comment]
Closing this issue since the modifications done for AddVhdxHardDisk.ps1 are merged as part of PR#376
