### ISSUE TITLE
update obsolete Get-AzureRmStorageUsage cmdlet global use

### ISSUE THREAD

**Issue by chvalean** [LIS/LISAv2#392]
[INFO ] Estimating storage account usage...
WARNING: Get global storage usage is obsolete, please use get location usage 
with -Location Parameter instead.

To be updated:
https://github.com/LIS/LISAv2/blob/master/Libraries/Azure.psm1#L270

**Comment by sireeshapotnuru** [comment]
Raised Pull Request #542
