### ISSUE TITLE
Hyper-V Setup Guideline

### ISSUE THREAD

**Issue by juhlee-microsoft** [LIS/LISAv2#399]
During Hyper-V test setup deployment from the scratch, there are a few steps are not documented in LISAv2. That could be one-time procedure. Let's create a draft contents first, and will decide if new contents add to existing document or new one. I recall they are about External vSwitch, memory size, etc. Please propose new context here. The goal is having new person successfully set up Hyper-V LISAv2 testbed.

**Comment by adriansuhov** [comment]
**For now, these are the 2 changes that I would like to make for README.md:**

### Prerequisite

1. You must have a Windows Machine (Host) with PowerShell (v5.0 and above) as test driver.

2. You must be connected to Internet.

3. You download 3rd party software in Tools folder. If you are using secure blob in Azure Storage Account or UNC path, you can add a tag <blobStorageLocation></blobStorageLocation> in any secret xml file.
* 7za.exe
* dos2unix.exe
* gawk
* jq
* plink.exe
* pscp.exe
* kvp_client32
* kvp_client64
* nc.exe

4. For running Azure tests, you must have a valid Windows Azure Subscription.

5. For running Hyper-V tests, the resource requirements are:
- Hyper-V role enabled
- At least 8 GB of memory on the Host - Most of lisav2 tests will create and start Virtual Machines (Guests) with 3.5 GB of memory assigned
- 1 External vSwitch in Hyper-V Manager/Virtual Switch Manager. This vSwitch will be named 'External' and must have an internet connection. For Hyper-V NETWORK tests you need 2 more vSwitch types created: Internal and Private. These 2 vSwitches will have the naming also 'Internal' and 'Private'.

----------------------------------------------------

### Prepare VHD for Your Test

> Applicable if you are uploading your own Linux VHD to Azure for test.

A VHD with Linux OS must be made compatible to work in HyperV environment. This includes:

* Linux Integration Services. If not available, at least KVP daemon must be running.
* Windows Azure Linux Agent (for testing in Azure environment only)
* SSH, and the SSH daemon configured to start on boot.
* Port 22 open in the firewall
* A regular user account on the guest OS
> "root" user cannot be used in the test configuration

Please follow the steps mentioned at [here](https://docs.microsoft.com/en-us/azure/virtual-machines/linux/create-upload-generic)

----------------------------------------------------
Feel free to add more to this info

**Comment by juhlee-microsoft** [comment]
@adriansuhov I put my comment in your post. I think it looks ok, please create a PR for document update.
