### ISSUE TITLE
.github folder not needed

### ISSUE THREAD

**Issue by ader1990** [LIS/LISAv2#413]
@juhlee-microsoft can we remove this folder?

**Comment by juhlee-microsoft** [comment]
I think so.

**Comment by juhlee-microsoft** [comment]
I think it's optional but other repositories use it for template files or yml files. Can we keep our yml file under here? Also we can plan to add some templates file for LISAv2.

**Comment by ader1990** [comment]
we cannot keep the azure pipeline file there, that is not github stuff. for the moment, I don t see any utility for that folder IMHO.

**Comment by juhlee-microsoft** [comment]
We are just not using the folder like other repo only, and I think we can remove it if we do not use. Just mentioned other repo’s case how they were used. Please open a PR for this removal. I will sign it off.


________________________________

**Comment by ader1990** [comment]
Created PR: https://github.com/LIS/LISAv2/pull/428

**Comment by chvalean** [comment]
Solved in https://github.com/LIS/LISAv2/pull/428
