### ISSUE TITLE
Add an email feature in LISAv2

### ISSUE THREAD

**Issue by juhlee-microsoft** [LIS/LISAv2#429]
The host system can handle the email notification like Jenkins typically. But sometimes it is good to have email notification from cmdline execution when it is done. I'd like to add email notification feature at the end of execution by using Outlook SMTP server. 

Please comment. @lizzha @simonxiaoss @chvalean @ader1990 @adriansuhov @mboitei

**Comment by simonxiaoss** [comment]
Now we use Jenkins to send email notifications.
We do have this feature in LISA but we did not use that feature very often. 
Close it.
