### ISSUE TITLE
Refactor lisav2 functions to one logical unit

### ISSUE THREAD

**Issue by ader1990** [LIS/LISAv2#441]
I have a suggestion to go even further and stabilize once and for all the framework code.

Remove AzureTestSuite.ps1 (move the code to other files, more info below)
Remove AutomationManager.ps1 (move the code to other files, more info below)
Remove Libraries/Framework-Hyperv.psm1 (move the code to other files, more info below)
Remove Libraries/Framework-Azure.psm1 (move the code to other files, more info below)
Remove Libraries/ExtensionLibrary.psm1 (these methods don t seem to be used anywhere)

Let's create a Libraries/LISAv2-Framework.psm1 file.
All the code from Libraries/Framework-Azure.psm1 should go into LISAV2-Framework.psm1

In Libraries/LISAv2-Framework.psm1 we should add the following methods:

Run-TestsOnCycle (from AzureTestSuite.ps1)
All the remaining contents from AzureTestSuite should be moved to Run-LISAV2.ps1, if there is too much code, refactor it into one method and move it to the Libraries/LISAv2-Framework.psm1
Get-SecretParams (from Libraries/Framework-Hyperv.psm1)
Parse-TestParameters (from Libraries/Framework-Hyperv.psm1)
Run-SetupScript (from Libraries/Framework-Hyperv.psm1)
Create-ConstantsFile (from Libraries/Framework-Hyperv.psm1)
Run-TestScript (from Libraries/Framework-Hyperv.psm1)
Collect-TestLogs (from Libraries/Framework-Hyperv.psm1)
Run-Test (from Libraries/Framework-Hyperv.psm1)
The following methods from Libraries/Framework-Hyperv.psm1:

Enable-RootUser should go to CommonFunctions.psm1
Create-HyperVCheckpoint should go to HyperV.psm1
Create-HyperVCheckpoint should go to HyperV.psm1
Check-IP should go to HyperV.psm1
Also, all the test cases should never use framework modules, only CommonFunctions.psm1. If they use some methods from the framework, they can break the framework logic.
All methods in the libraries that are not used anymore should be deleted.

Let's discuss on this @chvalean @lizzha @juhlee-microsoft @simonxiaoss and make these changes that will make all the code much cleaner and easier to understand/maintain.

**Comment by chvalean** [comment]
Completed in https://github.com/LIS/LISAv2/pull/440
