### ISSUE TITLE
nested_vm_utils.sh: aria2 package error on multiple distros

### ISSUE THREAD

**Issue by chvalean** [LIS/LISAv2#448]
When running test NESTED-KVM-BASIC-VERIFICATION on SLES12 SP3, it fails due to the aria2c binary not being present.
I don't see that package being in official SLES repo by default, so extra repos must be added for this to run on SLES.

'aria2' not found in package names. Trying capabilities.
No provider of 'aria2' found.
zypper_install aria2: Failed (exit code: 104)
Mon Nov 26 19:32:23 2018 : zypper_install aria2 Failed·(exit·code:·104)

nested_vm_utils.sh: line 79: aria2c: command not found 
[link](https://github.com/LIS/LISAv2/blob/master/Testscripts/Linux/nested_vm_utils.sh#L79)

Later edit:
Renamed issue as there is also an issue on CentOS 7.4 with the aria2 package:
There was a repo key change prompt if I manually ran to install the package afterwards, not sure if that's related.
Gallery image: CentOS Linux release 7.4.1708 (Core) - HPC gallery image.

No package aria2 available.
yum_install aria2: Failed (exit code: 1)
Wed Nov 28 15:13:42 2018 : yum_install aria2 Failed·(exit·code:·1)
nested_vm_utils.sh: line 79: aria2c: command not found

**Comment by asofron** [comment]
@LiliDeng  this should help for sles https://software.opensuse.org/download.html?project=network%3Autilities&package=aria2

**Comment by chvalean** [comment]
@LiliDeng do you have the capacity to close this in March?

**Comment by LiliDeng** [comment]
@chvalean Thanks for reminder, will finish it within March.

**Comment by juhlee-microsoft** [comment]
Close non-P0 issues
