### ISSUE TITLE
OOB document for Hyper-V

### ISSUE THREAD

**Issue by juhlee-microsoft** [LIS/LISAv2#474]
Using LISAv2 in local Hyper-V is more demanded. We need OOB (Out-of-box) procedure document update for new users. Deliverable is a new document helping the new user to create LISAv2 repo clone, complete Hyper-V setup, and can run LISAv2 tests in the local Hyper-V environment.

Additionally, it is nice to have for remote Hyper-V.

Example, External vSwitch for internet connection, etc.

**Comment by chvalean** [comment]
Created PR #638  with the documentation.
