### ISSUE TITLE
duplicate junit xmls in report folder

### ISSUE THREAD

**Issue by ader1990** [LIS/LISAv2#475]
For each lisav2 run, there is a duplicate junit file in the report folder: https://github.com/LIS/LISAv2/blob/master/Run-LisaV2.ps1#L222
If nobody uses one of those files, we should remove one.

**Comment by lizzha** [comment]
The XX-junit.xml is used by Jenkins. Not sure about the XX.xml, if it's not used, it can be removed.

**Comment by ader1990** [comment]
it has been removed in the refactor PR #568
