### ISSUE TITLE
Better log parsing in LSVMBUS test

### ISSUE THREAD

**Issue by juhlee-microsoft** [LIS/LISAv2#482]
Validate the test result better with the lsvmbus log. Make sure of the test result with lsvmbus log.

The ask is to copy the lsvmbus.log file.
Script is https://github.com/LIS/LISAv2/blob/master/Testscripts/Linux/LSVMBUS.sh

**Comment by chvalean** [comment]
Created a new feature request to handle new requirement for collecting logs in https://github.com/LIS/LISAv2/issues/524
