### ISSUE TITLE
Remove hardcoded root in cases so that we can remove the Enable-RootUser step for HyperV platform

### ISSUE THREAD

**Issue by lizzha** [LIS/LISAv2#484]
There’re some cases that use hardcoded root to run command or copy files remotely, e.g. KVP-PUSH-KEY-VALUES, SQM-BASIC. 
We need to fix them, and remove the Enable-RootUser step for HyperV platform

**Comment by LiliDeng** [comment]
#487

**Comment by asofron** [comment]
#507

**Comment by asofron** [comment]
Functional Tests - #533

**Comment by LiliDeng** [comment]
@asofron How many this work left? Is it okay now I remove enable-root for each provisioned VM?

**Comment by asofron** [comment]
Still have to post Network / Perf  @LiliDeng  , Will post the PR today . Once that is done we could remove enable-root

**Comment by asofron** [comment]
Network / Perf-Network - #555

**Comment by chvalean** [comment]
Changes done in mentioned PRs.
