### ISSUE TITLE
TestResult path is too long for Jenkins

### ISSUE THREAD

**Issue by ader1990** [LIS/LISAv2#489]
Stashing/Archiving artifacts is mandatory in order for the reporting and comparison pipelines to work.

Stashing/Archiving artifacts can break when the full path of the children leaves for TestResult folder goes beyond 255 characters, especially for long test case names and perf test cases.

Example test case result with path:
C:\Jenkins\workspace\mypipelinename_PR-500-ZP7CWWYIL7BDYIQTW5GZABHKP5IZWDQKBYJDUFXDIED7VK2J5RZA\TestResults\2018-04-12-09-33-58-6691\PERF-NETWORK-TCP-SINGLE-CONNECTION-THROUGHPUT-Synthetic\iperf3Data\iperf-client-tcp-IPv4-buffer-65536-conn-1-instance-1.txt

We have to minimize this issue somehow. Some options on how to do it:
1. Fix Windows nodes by executing: Set-ItemProperty -Path HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem -Name LongPathsEnabled  -Value 1
2. Reduce clutter from test case names
3. Reduce jenkins workspace root path length
4. Reduce the LISAv2 "2018-04-12-09-33-58-6691" like string

**Comment by chvalean** [comment]
this has been resolved by adding LongPathsEnabled registry entry.
