### ISSUE TITLE
Hyper-V: VMs left in running state if Setupscript is failing

### ISSUE THREAD

**Issue by adriansuhov** [LIS/LISAv2#490]
This is an extension of an issue raised here https://github.com/LIS/LISAv2/issues/438 and solved here https://github.com/LIS/LISAv2/pull/442 . However, we also need to cover the case if the test fail occurs during the setupscript run on Hyper-V. Right now the VMs are left running and after a few test runs the hosts will run out of resources

**Comment by juhlee-microsoft** [comment]
Close non-P0 issues
