### ISSUE TITLE
7za.exe can not extract file because the file path is not correct

### ISSUE THREAD

**Issue by juhlee-microsoft** [LIS/LISAv2#492]
12/05/2018 00:13:30 : [ERROR] Unexpected output from 7za.exe when creating **C:\LISAv2\DVAO52284\C:\Windows\TEMP\PERF-DPDK-FWD-PPS-DS15-636795656101414519.zip** :
12/05/2018 00:13:30 : [ERROR]  7-Zip (A) 9.20  Copyright (c) 1999-2010 Igor Pavlov  2010-11-18 Scanning  Creating archive C:\LISAv2\DVAO52284\C:\Windows\TEMP\PERF-DPDK-FWD-PPS-DS15-636795656101414519.zip   Error: 7-Zip cannot open file C:\LISAv2\DVAO52284\C:\Windows\TEMP\PERF-DPDK-FWD-PPS-DS15-636795656101414519.zip The filename, directory name, or volume label syntax is incorrect.     System error: Unspecified error  
12/05/2018 00:13:30 : [INFO ] Using user provided storage account key.
Get-Item : Cannot find path 
**'C:\Windows\TEMP\PERF-DPDK-FWD-PPS-DS15-636795656101414519.zip' because it 
does not exist.**
At C:\LISAv2\DVAO52284\Utilities\UploadFilesToStorageAccount.ps1:66 char:32
+         $LocalFileProperties = Get-Item -Path $fileName
+                                ~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Windows\TEMP...56101414519.z 
   ip:String) [Get-Item], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetIt 
   emCommand

**Comment by LiliDeng** [comment]
@juhlee-microsoft How to repro it?

**Comment by ader1990** [comment]
@juhlee-microsoft 

I think the problem is with the double paths -> C:\LISAv2\DVAO52284\C:\Windows\TEMP\PERF-DPDK-FWD-PPS-DS15-636795656101414519.zip ?

**Comment by LiliDeng** [comment]
Odd, I can't repro it locally.

**Comment by santoshx** [comment]
Not sure about this particular issue. But I had too many problems with 7za in the past. Make sure you use the version that didn't have problems before.

**Comment by ader1990** [comment]
@santoshx  as you can see in the logs, 7z is not the issue here, the path is the problem.

**Comment by juhlee-microsoft** [comment]
Correct

________________________________

**Comment by juhlee-microsoft** [comment]
Have not ever had this binary version issue. Can you write down detail of your error if different? It is nice to open an issue if you can not fix it immediately, Santosh


________________________________

**Comment by juhlee-microsoft** [comment]
Correct


________________________________

**Comment by juhlee-microsoft** [comment]
Because your repro is in local system not Jenkins slave. Adrian addresses the root-cause. Also check out my log, I pointed two paths conjunction.


________________________________
