### ISSUE TITLE
WALA agent config update dynamically for RDMA

### ISSUE THREAD

**Issue by juhlee-microsoft** [LIS/LISAv2#509]
WALA agent config /etc/waagent.config may be commented out like below.

: # Enable RDMA management and set up, should only be used in HPC images
: # OS.EnableRDMA=y

It blocks IB interface IP address obtaining.  RDMA tests should enable this parameter and restart the service. So that IB interface gets IP address.

**Comment by chvalean** [comment]
@juhlee-microsoft @adriansuhov maybe address this as part of the ongoing changes to RDMA automation code?

**Comment by juhlee-microsoft** [comment]
This idea comes from Shital originally, I would like to have new parameter '-CustomWALA' with https link in Run-Lisav2.ps1.

**Comment by juhlee-microsoft** [comment]
Close non-P0 issues
