### ISSUE TITLE
Implement timeout for each Test Case

### ISSUE THREAD

**Issue by adriansuhov** [LIS/LISAv2#521]
We need in the framework a timeout for each test case. RIght now, this covers only a small part:
- Only Bash scripts and Python scripts
- Only in Run-TestScript, the actual Run-LinuxCmd where the bash/python scripts are executed

We need to implement the following:
- A global timeout for each type of test script: powershell, bash & python
- This needs to cover all the operations that are performed on a test case run: executing setup scripts / sending files to VM / running the test script / running the cleanup script / collecting the test logs. In any of these steps a test hang can appear (from loss of connectivity, bad scripts/functions, etc).
- If a test case reaches its timeout, then it should be aborted and the framework should go to the next test case. The test summary log should state that it has been aborted by timing out

Right now we are seeing random test hangs in lisav2, for both Azure & Hyper-V tests so this change needs to cover all platforms. An xml tag should be added to each test case and maybe a default of ~10 minutes for the tests that don't have this timeout tag

**Comment by juhlee-microsoft** [comment]
Close non-P0 issues
