### ISSUE TITLE
Download retry times and wait time too long when VM can't access

### ISSUE THREAD

**Issue by LiliDeng** [LIS/LISAv2#564]
When the test VM can't access during test run, testing will still download files from it, the max retry times + wait time in each retry is too long

**Comment by lizzha** [comment]
@LiliDeng  Is this issue still valid? Please close it if not.

**Comment by LiliDeng** [comment]
Upload retry times 9 - 4 mins
Download retry times 19 - 9 mins
Should we reduce the retry max times for download files? @lizzha

**Comment by LiliDeng** [comment]
Not repro.
