### ISSUE TITLE
Remove WARN when HyperV VM group doesn't exist

### ISSUE THREAD

**Issue by santoshx** [LIS/LISAv2#575]
01/08/2019 07:43:00 : [INFO ] Checking if Hyper-V VM group 'LISAv2-OneVM12Disks-sx-FX40-636825499804' exists on localhost...
01/08/2019 07:43:01 : [WARN ] Hyper-V VM group LISAv2-OneVM12Disks-sx-FX40-636825499804 does not exist

Framework checks and WARNs when there isn't a pre-existing group.
As it is not mandatory to have a groups already created before starting the test this WARN should be removed.
A WARN can be added when there is already a preexisting group and framework is going to use it.

**Comment by chvalean** [comment]
@santoshx this should be a fairly easy fix in terms of handling messages in the code.
Can you work on it in between other tasks?

**Comment by santoshx** [comment]
@chvalean 
I can work on it but I need agreement from you and others that my thinking is correct!

**Comment by chvalean** [comment]
That entire sequence of messages is not the most clear one, example below.
Maybe try just to change WARN to INFO, unless we want to re-do that whole part just for this.

[INFO ] Creating HyperV Group : LISAv2-OneVM-hyper-v-XA30-636855331552.
[INFO ] Verifying that HyperV Group name is not in use.
[INFO ] Checking if Hyper-V VM group 'LISAv2-OneVM-hyper-v-XA30-636855331552' exists on localhost...
[WARN ] Hyper-V VM group LISAv2-OneVM-hyper-v-XA30-636855331552 does not exist
[INFO ] Using HyperV server : localhost

**Comment by juhlee-microsoft** [comment]
Close because we only hold P0
