### ISSUE TITLE
LTP test in Azure shows 'errno=EINVAL(22): Invalid argument' error

### ISSUE THREAD

**Issue by juhlee-microsoft** [LIS/LISAv2#582]
01/09/2019 13:37:09 : [INFO ] TEST SCRIPT SUMMARY ~~~~~~~~~~~~~~~
Running ltp lite suite
Total Tests: 173
Total Skipped Tests: 18
**Total Failures: 1**
Kernel Version: 4.15.0-1036-azure
Machine Architecture: x86_64
Hostname: LISAv2-OneVM-staginglisav2-NC13-20190109124617-role-0
Failed Tests:
proc01.c:396: read failed: /proc/self/task/1645/attr/selinux/current: errno=EINVAL(22): Invalid argument
proc01.c:396: read failed: /proc/self/task/1645/attr/selinux/prev: errno=EINVAL(22): Invalid argument
proc01.c:396: read failed: /proc/self/task/1645/attr/selinux/exec: errno=EINVAL(22): Invalid argument
proc01.c:396: read failed: /proc/self/task/1645/attr/selinux/fscreate: errno=EINVAL(22): Invalid argument
proc01.c:396: read failed: /proc/self/task/1645/attr/selinux/keycreate: errno=EINVAL(22): Invalid argument
proc01.c:396: read failed: /proc/self/task/1645/attr/selinux/sockcreate: errno=EINVAL(22): Invalid argument
proc01.c:396: read failed: /proc/self/task/1645/attr/smack/current: errno=EINVAL(22): Invalid argument
proc01.c:396: read failed: /proc/self/task/1645/attr/apparmor/prev: errno=EINVAL(22): Invalid argument
proc01.c:396: read failed: /proc/self/task/1645/attr/apparmor/exec: errno=EINVAL(22): Invalid argument
proc01.c:396: read failed: /proc/self/attr/selinux/current: errno=EINVAL(22): Invalid argument
proc01.c:396: read failed: /proc/self/attr/selinux/prev: errno=EINVAL(22): Invalid argument
proc01.c:396: read failed: /proc/self/attr/selinux/exec: errno=EINVAL(22): Invalid argument
proc01.c:396: read failed: /proc/self/attr/selinux/fscreate: errno=EINVAL(22): Invalid argument
proc01.c:396: read failed: /proc/self/attr/selinux/keycreate: errno=EINVAL(22): Invalid argument
proc01.c:396: read failed: /proc/self/attr/selinux/sockcreate: errno=EINVAL(22): Invalid argument
proc01.c:396: read failed: /proc/self/attr/smack/current: errno=EINVAL(22): Invalid argument
proc01.c:396: read failed: /proc/self/attr/apparmor/prev: errno=EINVAL(22): Invalid argument
proc01.c:396: read failed: /proc/self/attr/apparmor/exec: errno=EINVAL(22): Invalid argument
proc01.c:465: readproc() failed with 18 errors.
01/09/2019 13:37:09 : [INFO ] END OF TEST SCRIPT SUMMARY ~~~~~~~~~~~~~~~

**Comment by lizzha** [comment]
It's the LTP case "proc01" that reads the entries under
	"/proc/self/attr/*",
	"/proc/self/task/[0-9]*/attr/*",
if the VM has both SELinux libraries and headers, and gets "Invalid argument" error for some of them.
It's seems not something to fix in LISAv2.

**Comment by juhlee-microsoft** [comment]
Can not reproduce this issue any more. Tested below pipeline and they are all passed.

https://penguinator.westus2.cloudapp.azure.com/job/Microsoft-Test-Execution-Pipeline/632/
https://penguinator.westus2.cloudapp.azure.com/job/Microsoft-Test-Execution-Pipeline/633/
https://penguinator.westus2.cloudapp.azure.com/job/Microsoft-Test-Execution-Pipeline/634/

I think we can close this issue.
