### ISSUE TITLE
NTTTCP Test failing to execute for multiple connections

### ISSUE THREAD

**Issue by iamshital** [LIS/LISAv2#585]
**Location**
https://github.com/LIS/LISAv2/blob/master/Testscripts/Linux/perf_ntttcp.sh#L272 

**Problem**
NTTTCP test is only running test for 1 connection and not proceeding for further connections.

**Error Code:** 
./perf_ntttcp.sh: line 272: "0" + 1: syntax error: operand expected (error token is ""0" + 1")

**Comment by LiliDeng** [comment]
because current script support this way (1,2,4,8)
