### ISSUE TITLE
Limit LISAv2 excessive logging

### ISSUE THREAD

**Issue by ader1990** [LIS/LISAv2#590]
There are too many info logs that do make the log reading very hard.

Stages to achieve this:
1. Limit kernel boot log output to warning/error/fail
2. Add a flag to lisav2 -LogLevel 1|2|3|4

1 - Error only
2 - Warn and Error
3 - Warn, Error, Info : DEFAULT one
4 - Warn, Error, Info, Verbose
5 - Warn, Error, Info, Verbose, Debug

@lizzha @LiliDeng please comment if you consider this necessary or not.

I consider 1st stage necessary on hyperv and is already implemented by PR #614

**Comment by lizzha** [comment]
Wasn't aware that I closed it by accident.
Better to use words for the value of -LogLevel, e.g. Error|Warn|Info|Verbose|Debug, descending ordered by severity. 
If one level is specified, all the logs with the same or higher severity will be printed.

**Comment by chvalean** [comment]
@juhlee-microsoft should we go ahead and close this enhancement idea?
It would be a nice to have feature, but since the priority on issues for lisav2 has changed, this one might no longer have to be implemented.

**Comment by juhlee-microsoft** [comment]
Unfortunately, I can not hold other issues unless P0. I believe this is one of them doing good for usability though.
