### ISSUE TITLE
Move Hyper-V related methods from Libraries/IntegrationServiceLibrary.psm1 to Libraries/Hyperv.psm1

### ISSUE THREAD

**Issue by ader1990** [LIS/LISAv2#592]
The following methods are all relying on HyperV being installed and mostly apply to a VM, thus sohuld be moved in the HyperV module:

1. Set-VMDynamicMemory
2. Get-VMDemandMemory
3. Get-GuestInterfaceByVSwitch
4. Get-IPv4ViaKVP
5. Get-IPv4AndWaitForSSHStart
6. Wait-ForVMToStartKVP
7. Wait-ForVMToStop
8. Get-ParentVHD
9. Create-ChildVHD
10. Create-Controller
11. Copy-FileVM
12. Copy-CheckFileInLinuxGuest
13. New-BackupSetup
14. New-Backup
15. Restore-Backup
16. Check-VMStateAndFileStatus
17. Remove-Backup
18. Get-BackupType
19. Get-DriveLetter
20. Get-KVPItem
21. Set-IntegrationService

**Comment by lizzha** [comment]
These are LIS feature related functions, so I moved them to IntergationServiceLibraries.psm1. 
Per offline discussion, @ader1990  will rename the file to a more proper name, e.g. HypervLis.psm1, and move unrelated functions to HyperV.psm1

**Comment by chvalean** [comment]
Not going to pursue framework level changes/refactor, closing this item.
