### ISSUE TITLE
STRESSTEST-WEB-PARALLEL-ACCESS: nginx package not available

### ISSUE THREAD

**Issue by adriansuhov** [LIS/LISAv2#593]
While running STRESSTEST-WEB-PARALLEL-ACCESS on a CentOS 7.5, I found that the test was ABORTED because of a config issue. This is the faulty code:
https://github.com/LIS/LISAv2/blob/master/Testscripts/Windows/STRESS-Web.ps1#L124
But on the VM we have the following message: _"No package nginx available."_

This happens because an additional step must be performed on CentOS/RHEL - Adding nginx repo.

**Comment by asofron** [comment]
Apparently http_load work fine only with debian based distros

**Comment by chvalean** [comment]
Until further requirement to support this test on other distributions, restrict it only to Debian/Ubuntu.
CentOS/Redhat will require epel repo setup to install nginx and further automation code.
