### ISSUE TITLE
PERF-NETWORK-UDP-THROUGHPUT-MULTICONNECTION-Synthetic/SRIOV failure.

### ISSUE THREAD

**Issue by mbivolan** [LIS/LISAv2#595]
When running  the test on Hyper-V we observed that it fails when it tries to collect the mac addresses from a VM with more than one nic.

The test throws the following error:
EXCEPTION : Exception calling "Insert" with "2" argument(s): "Collection was of a fixed size." at line: 1049

This is the failing code:
https://github.com/LIS/LISAv2/blob/a33493d65ac288a2ed5de19321037eb59583261a/Libraries/HyperV.psm1#L1049

**Comment by chvalean** [comment]
Fixed in PR #596
