### ISSUE TITLE
hyperv: bring back snapshot feature

### ISSUE THREAD

**Issue by ader1990** [LIS/LISAv2#599]
Before PR #568 , if a test case failed on HyperV, a snapshot was created with the failure and for the following test the VM was reverted to its original pre test state.

We need to bring back that feature.

**Comment by chvalean** [comment]
Side-effect or related to the same issue is this behavior:
'If a test case is Failed/Aborted on a setup type and the next test is on the same setup type LISAv2 will attempt to create a new VM instead of using the existing one and reverting to initial snapshot'
