### ISSUE TITLE
azure:  add support for snapshots

### ISSUE THREAD

**Issue by ader1990** [LIS/LISAv2#600]
Like on HyperV, we can speed up tests if we can reuse the same VM. But to make sure the VM state is unaffected by the previous test case run, we need to implement checkpoint/restore workflow.

**Comment by iamshital** [comment]
I'm aware that, azure supports VHD snapshots but not aware of VM snapshot. 
Have you checked, if azure supports this?

**Comment by ader1990** [comment]
yes, I have checked the feature, but it takes a huge amount of time to snapshot and revert the VM (more than 15minutes). It s way faster to create another deployment than use the feature.

**Comment by ader1990** [comment]
Closing issue, as it is faster to create the deployment from scratch than to snapshot the vms.
