### ISSUE TITLE
Duplicated IP addresses in multiple VM setup (RDMA)

### ISSUE THREAD

**Issue by juhlee-microsoft** [LIS/LISAv2#613]
@adriansuhov  found below duplicated IP addresses.

The example slaves list from constants.sh after removing comma. 10.0.0.16 and 10.0.0.28 are duplicated. Should fix not to have duplicated ones.

10.0.0.10
10.0.0.11
10.0.0.12
10.0.0.14
10.0.0.15
**10.0.0.16
10.0.0.16**
10.0.0.17
10.0.0.18
10.0.0.19
10.0.0.20
10.0.0.21
10.0.0.22
10.0.0.23
10.0.0.24
10.0.0.25
10.0.0.26
**10.0.0.28
10.0.0.28**
10.0.0.30
10.0.0.31
10.0.0.32
10.0.0.33
10.0.0.4
10.0.0.5
10.0.0.6
10.0.0.7
10.0.0.8
10.0.0.9

**Comment by adriansuhov** [comment]
It is a framework issue. This is taken from PS console, after the test was finished. As you can see, $AllVMData is already tainted as it's passed to the test script:
PS C:\Users\v-adsuho\Documents\rdma\latest2> $AllVMData.InternalIP
**10.0.0.16**
10.0.0.32
10.0.0.26
10.0.0.33
10.0.0.25
10.0.0.11
10.0.0.19
10.0.0.18
10.0.0.7
10.0.0.21
**10.0.0.16**
**10.0.0.28**
10.0.0.9
10.0.0.15
10.0.0.6
10.0.0.10
10.0.0.22
10.0.0.5
10.0.0.23
10.0.0.24
10.0.0.17
**10.0.0.28**
10.0.0.4
10.0.0.31
10.0.0.12
10.0.0.8
10.0.0.14
10.0.0.20
10.0.0.30
10.0.0.27

**Comment by chvalean** [comment]
Resolved in PR #619
