### ISSUE TITLE
Verify function Get-IPv4AndWaitForSSHStart in test functionality

### ISSUE THREAD

**Issue by chvalean** [LIS/LISAv2#626]
Get-IPv4AndWaitForSSHStart is used many times across the test cases: https://github.com/LIS/LISAv2/search?q=Get-IPv4AndWaitForSSHStart&unscoped_q=Get-IPv4AndWaitForSSHStart

Get-IPv4AndWaitForSSHStart returns an IP or $false (it does not throw). all the calls to the method must be verified and updated if needed.

---

When running STRESSTEST-CHANGE-MTU-RELOAD-NETVSC the test will get aborted and this is the lisav2 log when that occurs.
VM IP does not change after test run.

Function: https://github.com/LIS/LISAv2/blob/master/Libraries/IntegrationServiceLibrary.psm1#L248

[hyperv] 01/18/2019 22:10:31 : [INFO ] dos2unix reload_netvsc.sh && sleep 5 && bash reload_netvsc.sh is running in background with ID 859 ...
[hyperv] Access denied01/18/2019 22:20:34 : [ERROR] Get-IPv4AndWaitForSSHStart: SSH is not working correctly after boot up
[hyperv] 01/18/2019 22:20:34 : [INFO ] Successfully reloaded hv_netvsc for 25 times

Can be repro'd with ubuntu 18.04.1 on Hyper-V

**Comment by asofron** [comment]
Seeing other test cases using Get-IPv4AndWaitForSSHStart work fine only STRESSTEST-CHANGE-MTU-RELOAD-NETVSC had the issue

**Comment by asofron** [comment]
All issues with  Get-IPv4AndWaitForSSHStart in testcases has been fixed
