### ISSUE TITLE
custom-kernel: Install fails if the VMs have a static name

### ISSUE THREAD

**Issue by adriansuhov** [LIS/LISAv2#632]
When running lisav2 with custom kernel option, if the tests have setup types that have static VMs name (e.g. dependency-vm), the framework will not download the kernel install log file (starting from second test). Without downloading the logs, it will not check if the install is successful or not & will output an error that kernel failed to install on 1 VM.
The line that is causing the issue is this: https://github.com/LIS/LISAv2/blob/master/Libraries/CommonFunctions.psm1#L618
As you can see, it will only downloads the logs if the file doesn't exist. The logs will be downloaded for the first test, but from the second one onwards, errors will start to show up (because of L623 - where it will not increment $kernelSuccess variable). The file already exists from the first test, and the code will not enter the "if" branch from L618

The custom kernel install logs will be placed in the upper testResults\[date] folder, rather in the [date]\test_name folder as in the past.

**Comment by chvalean** [comment]
@lizzha this seems to have been introduced with the lisav2 refactor.
Will you be able to have a look by chance?
CC @LiliDeng
Thank you!

**Comment by LiliDeng** [comment]
@chvalean do you have repro job link or repro command?

**Comment by adriansuhov** [comment]
@LiliDeng , I'll talk to you in private

**Comment by lizzha** [comment]
The kernel is built when VM is deployed, not when every case runs. So it’s not proper to put the buildkernel logs under case folders.
The fix for this problem can be to use unique log file name for dependency-vm, e.g. LISAv2-OneVM-adsuhuTest-VC74-20190121065806-dependency-vm-build-CustomKernel.txt, then the log will not be overwritten.

**Comment by chvalean** [comment]
Fixed in PR #662
