### ISSUE TITLE
Azure: VM size series needs better framework design

### ISSUE THREAD

**Issue by juhlee-microsoft** [LIS/LISAv2#645]
Upon new VM size added to the list of LISAv2, we used 'if-statement' with 'else-if'. Suggest to use "pattern" in the automation not continue on adding else-if statement.

**Comment by iamshital** [comment]
@juhlee-microsoft What is this about? Please point out the source file and line.

**Comment by juhlee-microsoft** [comment]
@iamshital Please see PR #643

**Comment by lizzha** [comment]
It can be refactored to use switch block with regex pattern match, also the line https://github.com/LIS/LISAv2/blob/master/Libraries/Azure.psm1#L106 duplicates multiple times

@LiliDeng could your team take this?

**Comment by LiliDeng** [comment]
@lizzha Got it.
