### ISSUE TITLE
Enable "Hyper-V" tests

### ISSUE THREAD

**Issue by juhlee-microsoft** [LIS/LISAv2#67]
We are excited to release Linux GOS automation in Hyper-V in Jenkins.

- [x] Import Test Cases to LISAv2 xml file
- [x] Validate existing LISAv2 tests for Hyper-V
- [x] Validate Azure regression test during import Hyper-V tests.
- [ ] Enable SRIOV support for HyperV
- [ ] Enable Passthrough disk support for HyperV
- [x] Enable LISAv2 framework to run HyperV tests
- [x] Define test coverage/scope

**Comment by chvalean** [comment]
@juhlee-microsoft  let's move the PCI passthrough outside of this. We'll be working on those scenarios when we schedule the specific test areas.
Everything else from the list has been completed, we should close this item.
