### ISSUE TITLE
BVT-LIS-DRIVER-VERSION-CHECK fails on Ubuntu

### ISSUE THREAD

**Issue by ader1990** [LIS/LISAv2#704]
This TC should not fail on non-RHEL distros.

**Comment by chvalean** [comment]
This is the candidate for test skipped state if distro is anything other than RedHat or CentOS.
This is expected as test requires LIS RPMs, and current exit status is either Abort or Fail, thus requiring a Skipped state

**Comment by chvalean** [comment]
This will be part of Skipped state support from #355
