### ISSUE TITLE
Framework: Incorrect handling of Test Results

### ISSUE THREAD

**Issue by iamshital** [LIS/LISAv2#709]
If the test is PASS and if there is subtest results are present, SQL query generated is wrong.

INSERT INTO LISAv2Results (DateTimeUTC,TestPlatform,TestLocation,TestCategory,TestArea,TestName,**TestResult**,SubTestName,SubTestResult,ExecutionTag,GuestDistro,KernelVersion,LISVersion,HostVersion,VMSize,Networking,ARMImage,OsVHD,LogFile,BuildURL) VALUES ('2019-2-7 8:4:23','Azure','southcentralus','BVT','BVT','BVT-VERIFY-DEPLOYMENT-PROVISION','**@{TestResult=PASS; TestSummary=	FirstBoot : PASS <br />	FirstBoot : Call Trace Verification : PASS <br />	Reboot : PASS <br />	Reboot : Call Trace Verification : PASS <br />}**','','','','Ubuntu 16.04.5 LTS (Xenial Xerus)','4.15.0-1036-azure','NA','14393-10.0-0-0.274','Standard_DS1_v2','Synthetic','Canonical UbuntuServer 16.04-LTS latest','','https://XXXXXXXXX.blob.core.windows.net/lisav2logs/2019-2-7/BVT-VERIFY-DEPLOYMENT-PROVISION-636851234631095316.zip', 'https://XXXXXXXXX.XXXXXX.XXXXXX.azure.com/job/job-azuretest/job/job-cloudtest-auto/26329/consoleFull')

**Comment by iamshital** [comment]
**Note:** Removing P0 flag. I thought it was present in master branch.
Assigning to @ader1990 as the issue is present in `ader1990:implement_skipped_tc_state`

**Comment by iamshital** [comment]
Also the test summary is wrong : 
```
[LISAv2 Test Results Summary]
Test Run On           : 02/07/2019 07:55:50
ARM Image Under Test  : Canonical : UbuntuServer : 16.04-LTS : latest
Total Test Cases      : 2 (1 Passed, 0 Failed, 0 Aborted, 1 Skipped)
Total Time (dd:hh:mm) : 0:0:12

   ID TestCaseName                                                                TestResult TestDuration(in minutes) 
---------------------------------------------------------------------------------------------------------------------
    1 BVT-LIS-DRIVER-VERSION-CHECK                                                   SKIPPED                 1.39 
    2 BVT-VERIFY-DEPLOYMENT-PROVISION                                   @{TestResult=PASS; TestSummary=	FirstBoot : PASS 
	FirstBoot : Call Trace Verification : PASS 
	Reboot : PASS 
	Reboot : Call Trace Verification : PASS 
}                 3.02 


Logs can be found at C:\LISAv2\GO92\TestResults\2019-07-02-07-55-46-6637
```

**Comment by ader1990** [comment]
I will close this issue as this refers to a in-progress pr, not merged one. @iamshital  this will be resolved in the PR itself.

**Comment by ader1990** [comment]
@iamshital can you check if the new fixes are alright? thanks.
