### ISSUE TITLE
Fix the value of the test case results

### ISSUE THREAD

**Issue by ader1990** [LIS/LISAv2#711]
Because of the refactor related to how test cases return the status results, the following tests need to be fixed in order to return proper statuses:

1. BVT-VERIFY-VHD-PREREQUISITES  Test case script result does not match known ones:>>>   PASS<<<
2. BVT-VERIFY-SSHD-CONFIG Test case script result does not match known ones:>>>   PASS<<<
3. BVT-CORE-RELOAD-MODULES-SMP Test case script result does not match known ones:>>> 157 PASS<<<
4. BVT-NET-IFUP-IFDOWN Test case script result does not match known ones:>>>2015<<<

**Comment by lizzha** [comment]
@xian123  could you please take this?

**Comment by ader1990** [comment]
BVT-CORE-RELOAD-MODULES-SMP fixed by PR https://github.com/LIS/LISAv2/pull/730

**Comment by xian123** [comment]
The test cases are fixed by PR #739 @lizzha
