### ISSUE TITLE
Fix CI pipelines failure when LISA exits with exit code 0

### ISSUE THREAD

**Issue by mbivolan** [LIS/LISAv2#717]
This error appears on both Jenkins and Azure DevOps.

Problem: When all the LISA tests are passed and LISA finishes execution with exit code 0, the wrapper stage still fails.
Cause: This might be caused by the Error global variable being populated by error outputs from binaries.

**Comment by ader1990** [comment]
The problem has been identified:
https://github.com/LIS/LISAv2/blob/master/LISAv2-Framework.psm1#L246

This code breaks the PowerShell wrapper,  exiting with exit code 1.
```
Get-Variable -Exclude PWD,*Preference,ExitCode -Scope "Global" | Remove-Variable -Scope "Global" `
				-Force -ErrorAction SilentlyContinue
```

Longterm fix:
The test controller should clear all the global variables it has set.

Quick fix: remove this line

**Comment by ader1990** [comment]
Fixed by: https://github.com/LIS/LISAv2/pull/732
