### ISSUE TITLE
Replaceable test parameters can also replace test case names

### ISSUE THREAD

**Issue by ader1990** [LIS/LISAv2#723]
The current implementation of Replaceable test parameters looks for the key to be replaced in all the config XML and will arbitrarily replace any string in that XML:
https://github.com/LIS/LISAv2/blob/master/TestControllers/TestController.psm1#L237

For example, if a test case name contains a replaceable test parameter key, the test case name itself will be different.

Possible fix: Make sure that XML items are changed and not substrings.

**Comment by lizzha** [comment]
Ideally the replaceable parameters should only replace the values under <TestParameters> tag, but there's exception in cases in FunctionalTests-InfiniBand.xml. The cases has <NumberOfReboots>INFINIBAND_INTEL_TOTAL_REBOOT_COUNT</NumberOfReboots> not under <TestParameters>.
If we can move the INFINIBAND_INTEL_TOTAL_REBOOT_COUNT under <TestParameters>, then we can update to only replace parameters under <TestParameters>

**Comment by chvalean** [comment]
@juhlee-microsoft @adriansuhov can you please ack this and transform NumberOfReboots as a test param, not part of the main test definition part.

**Comment by juhlee-microsoft** [comment]
Acked, @adriansuhov and I work on new branch merging to master soon. We can make a change in new PR. Sounds better?

**Comment by juhlee-microsoft** [comment]
PR #736

**Comment by ader1990** [comment]
@juhlee-microsoft  How is PR 736 fixing the issue?

**Comment by iamshital** [comment]
> PR #736

This PR doesn't resolve the issue.
Actually, Adrian is right. If the "Replaceable Key" is present in testname, then it will replace the testname as well.

**Comment by iamshital** [comment]
https://github.com/LIS/LISAv2/pull/748 Probably this will fix.
