### ISSUE TITLE
File referred by ".\" are not resulting to wrong path.

### ISSUE THREAD

**Issue by iamshital** [LIS/LISAv2#73]
Issue: When we launch the automation in powershell, the files referred with `.\some-file-path"` are getting referred wrongly. If the PS window is elevated then it refres as : `C:\WINDOWS\system32\some-file-path`.
If the PS window is not elevated then it refers as `C:\users\<username>\some-file-path`.

But the code behaves as expected when launched from Jenkins / VScode debugger.

Resolution: Identify the root cause and fix the problem
Or, refer files by their absolute path.

**Comment by ader1990** [comment]
@iamshital please close this issue, if it has been addressed already (I see it has been addressed)
