### ISSUE TITLE
Don't use IsWindows global as it s reserved in PowerShell 6

### ISSUE THREAD

**Issue by ader1990** [LIS/LISAv2#731]
We should rename the IsWindows global variable as this variable is reserved on PowerShell 6

https://github.com/PowerShell/PSScriptAnalyzer/blob/9acf387b33147000e30753af84befdcfaabe28be/Rules/AvoidAssignmentToAutomaticVariable.cs#L33

https://github.com/PowerShell/PowerShell/blob/master/CHANGELOG.md#v030---2016-04-11

**Comment by chvalean** [comment]
@LiliDeng @lizzha I think you introduced this as part of the nested test cases.
Can you please ack and fix?
Thank you!

**Comment by LiliDeng** [comment]
@chvalean thanks, we used Desktop version by default not Core version of PowerShell? we need disable the collect log part when L1 VM is windows os.

**Comment by lizzha** [comment]
@LiliDeng the fix would be to use a different variable name as it's reserved

**Comment by LiliDeng** [comment]
#752 merged, so close it.
