### ISSUE TITLE
$customLISBranch is always empty, and in shell script it will use master branch.

### ISSUE THREAD

**Issue by LiliDeng** [LIS/LISAv2#738]
@ader1990 @lizzha We can pass -CustomLIS, but can't pass the branch name in current code, not sure if we need add another parameter like -CustomLIS or specify it in -CustomParameters  #737

**Comment by chvalean** [comment]
@iamshital are you using this in the LIS pipeline?
Otherwise I'm not aware of using this on our end.

**Comment by LiliDeng** [comment]
I use it when run VERIFY-NVIDIA-CUDA-DRIVER-FOR-NC12/24/24r-VM cases against centos and redhat 7.5, from this guideline [Here](https://github.com/MicrosoftDocs/azure-docs/blob/master/articles/virtual-machines/linux/n-series-driver-setup.md), need install latest LIS, I tried, it downloaded 4.2.8 it didn't work, using 4.3.0, it works. So that's why I found I can't specify the branch name during testing.

**Comment by iamshital** [comment]
We had -CustomLISBranch parameter in earlier automation. But, I don't recommend to add it back. I propose to support `-CustomLIS "lisnext\master"`. 

@LiliDeng  @chvalean  Let me know.

**Comment by chvalean** [comment]
lisnext\branch sounds like a good option to me, just needs to be documented as well.
If \branch is not specified, the code should default to master branch.

**Comment by iamshital** [comment]
PR opened #823

**Comment by juhlee-microsoft** [comment]
Close non-P0 issues
