### ISSUE TITLE
Select Azure subscription

### ISSUE THREAD

**Issue by juhlee-microsoft** [LIS/LISAv2#74]
Add 4x text boxes in UI; Application Name, Client ID, Secret Key, Tenant ID

If it is using Microsoft subscription and our own secret, they should be empty.
If partner uses new values, we will fetch their subscription with entries for further testing.
We do not store partner's credential.

**Comment by ader1990** [comment]
@juhlee-microsoft is this a lisav2 issue? if it isn't, it should be closed
