### ISSUE TITLE
Need new parameter OverrideVMSize in LISAv2 cmdline

### ISSUE THREAD

**Issue by juhlee-microsoft** [LIS/LISAv2#750]
PS C:\Users\juhlee\Source\Repos\LISAv2\Utilities> .\Get-LISAv2Statistics.ps1 |grep -i gpu
VERIFY-NVIDIA-CUDA-DRIVER-FOR-NC6-VM                                                  Azure      Functional             GPU                           gpu,pci_hyperv     1
VERIFY-NVIDIA-CUDA-DRIVER-FOR-NC12-VM                                                 Azure      Functional             GPU                           gpu,pci_hyperv     1
VERIFY-NVIDIA-CUDA-DRIVER-FOR-NC24-VM                                                 Azure      Functional             GPU                           gpu,pci_hyperv     1
VERIFY-NVIDIA-CUDA-DRIVER-FOR-NC24r-VM                                                Azure      Functional             GPU                           gpu,pci_hyperv     1
gpu                            4
PS C:\Users\juhlee\Source\Repos\LISAv2\Utilities>

For example, 4 GPU test cases are from a single test script, but just a modified with VM Size. This happens in RDMA IB tests also. If we have a new input Parameter in cmd line and override the VMsize, it will reduce the copy-and-paste style test cases in xml file.
New design also need default value; if <OverrideVMSize> is defined, it will follow the existing value. Otherwise, it should load common use VMSize.

**Comment by chvalean** [comment]
discussed in a meeting this, lisav2 has a -OverrideVMSize flag
