### ISSUE TITLE
Need MSI/MSI-X interrupt test

### ISSUE THREAD

**Issue by juhlee-microsoft** [LIS/LISAv2#751]
Validate MSI/MSI-X interrupts in existing SR-IOV and GPU test cases.

Take a snapshot of /proc/interrupts
Load or unload VF driver or GPU driver; or running traffic over VF.
Wait a few seconds. If there is any traffic running, wait for minutes.
Take another snapshot of the interrupts.

Compare each and verify at least 1 interrupt per device should be increased.
if nvme, it will show an interrupt per vmne device. 
validate interrupt counts increment evenly overall CPU named lines.
validate the same condition in irq in the file.

**Comment by chvalean** [comment]
@juhlee-microsoft  can you please create a TFS task for this and close this?

**Comment by juhlee-microsoft** [comment]
Done. Sent the internal email for new task item.
