### ISSUE TITLE
Fix test-cases support for SLES

### ISSUE THREAD

**Issue by asofron** [LIS/LISAv2#756]
Following testcases should also checked and have support for SLES : 

- INITRD-MODULES-CHECK
Thu Feb 14 14:07:36 2019 : The test parameter hv_modules is not defined in constants file.
- KVP-BASIC-CHECKS
Error: kvp_client64 tool is not on the system
Error: kvp_client64 tool is not on the system
- BVT-VERIFY-UUID-FSTAB 
Has only support for sles 15 , maybe also add sles12

**Comment by LiliDeng** [comment]
Fix BVT-VERIFY-UUID-FSTAB against SLES12.3 is in progress.

**Comment by LiliDeng** [comment]
#808

**Comment by LiliDeng** [comment]
All fix merged, so close this.
