### ISSUE TITLE
HyperV: RHEL distros need to be registered before using them

### ISSUE THREAD

**Issue by iamshital** [LIS/LISAv2#759]
HyperV tests are failing due to RHEL local VHDs are not registered to receive the software packages.

Fix needed:
1. Add support to register local RHEL VHDs.

**Comment by chvalean** [comment]
This is what we used in LIS deploy tests in lis-test:
https://github.com/LIS/lis-test/blob/master/WS2012R2/lisa/remote-scripts/ica/Register_vm_rhel.sh

**Comment by iamshital** [comment]
@chvalean Thank you Chris. We're working on getting this into LISAv2.

**Comment by iamshital** [comment]
Fixed by #768
