### ISSUE TITLE
Upload test results to database in framework level

### ISSUE THREAD

**Issue by lizzha** [LIS/LISAv2#760]
Now test results are uploaded by each case, it should be handled in framework level

**Comment by chvalean** [comment]
@lizzha can you please close this one if the PR is enough, or create a new feature addition for the other test to move to the new model?

**Comment by lizzha** [comment]
The PR is only a pilot. Performance cases and nested cases need to be updated to use the new model.

**Comment by juhlee-microsoft** [comment]
Close non-P0 issues
