### ISSUE TITLE
Testcase result is getting updated to aborted, since $resultPass is null

### ISSUE THREAD

**Issue by sireeshapotnuru** [LIS/LISAv2#763]
Current LISAv2 Framework has removed $resultPass,$ resultFail variables,
So, Even though Testcase is passed , Testcase result is getting updated to aborted.
 
02/16/2019 02:15:09 : [INFO ] Info: VM memory changed successfully!
**02/16/2019 02:15:09 : [INFO ] Test case script result does not match known ones: Aborted
02/16/2019 02:15:09 : [ERROR] Failed to retrieve a known test result: Aborted**

**Comment by LiliDeng** [comment]
I will update code for this, the global name changed 
		Set-Variable -Name ResultPassed  -Value $passResult -Scope Global
		Set-Variable -Name ResultSkipped -Value $skippedResult -Scope Global
		Set-Variable -Name ResultFailed  -Value $failResult -Scope Global
		Set-Variable -Name ResultAborted -Value $abortedResult -Scope Global

**Comment by LiliDeng** [comment]
@sireeshapotnuru Could you please let know which test cases you run hit issues?

**Comment by iamshital** [comment]
@LiliDeng , Are you going to work on this today?

**Comment by iamshital** [comment]
Because, we're blocked on other P0 task, that depends on this task.

**Comment by LiliDeng** [comment]
@iamshital I am working on it, and could you please list which test cases you hit issue, then I can run testing against updated code.

**Comment by LiliDeng** [comment]
If you already start working one this, then I will un assign it to me.

**Comment by iamshital** [comment]
I haven't started working. @sireeshapotnuru , Please list the test cases.

**Comment by LiliDeng** [comment]
We will create PR for this soon, I doubt that some cases will hit issues which the same with this PR #739 fixed

**Comment by iamshital** [comment]
@LiliDeng , Do we need to fix this in test cases or in LISA2 framework?

**Comment by LiliDeng** [comment]
Per @ader1990 , we need fix them in test cases.

**Comment by iamshital** [comment]
That is bad. @ader1990 , Could you please explain this?

**Comment by lizzha** [comment]
why not update the global variable name back, since they're already used in muliple cases
ResultPassed  -> ResultPass
ResultFailed  -> ResultFail

**Comment by LiliDeng** [comment]
Ok, I will take update the global name task firstly, for specify test cases like https://github.com/LIS/LISAv2/pull/739  @sireeshapotnuru will confirm the owneship with Chris about this,

**Comment by sireeshapotnuru** [comment]
@LiliDeng  Below all the list of Testcases where we need fix

        LIVEMIGRATE
        LIVEMIGRATE-FAILOVER
        LIVEMIGRATE-MEM4GB-CORE8
        LIVEMIG_MEM8GB_CORE16
        LIVEMIG_MEM16GB_CORE32
        QUICKMIGRATE
        COPYFILE-DURING-MIGRATION
        QUICKMIG_MEM4GB_CORE8
        QUICKMIG_MEM8GB_CORE16
        QUICKMIG_MEM16GB_CORE32
        SECUREBOOT-BASIC
        SECUREBOOT-UPDATE-KERNEL
        SECUREBOOT-VSS
        SECUREBOOT-MIGRATEVM
        PRODUCTION-CHECKPOINT-FAILBACK
        PRODUCTION-CHECKPOINT
        PRODUCTION-CHECKPOINT-EXT4
        PRODUCTION-CHECKPOINT-BTRFS
        PRODUCTION-CHECKPOINT-IDE_SCSI
        PRODUCTION-CHECKPOINT-VHDX_XFS
        PRODUCTION-CHECKPOINT-ISO-NONETWORK
        PRODUCTION-CHECKPOINT-3CHAIN-VHD
        PRODUCTION-CHECKPOINT-iSCSI
        RUNTIME_MEM_HOTADD
        RUNTIME_MEM_HOTREMOVE
        RUNTIME_MEM_SMALLINCREASE128
        RUNTIME_MEM_SMALLDECREASE128
        RUNTIME_MEM_SMALLINCREASE100
        RUNTIME_MEM_SMALLDECREASE100
        RUNTIME_MEM_MULTIPLEADDREMOVE
        RUNTIME_MEM_STRESSHOTREMOVE
        RUNTIME_MEM_HOTADD_REBOOT
        DYNAMIC-MEMORY-VERIFY-UDEV
        DYNAMIC-MEMORY-HOT-ADD
        DYNAMIC-MEMORY-HOTADD-STRESS-APP
        DYNAMIC-MEMORY-STRESS-HOTADD-5SECONDS
        DYNAMIC-MEMORY-STRESS-HOTADD-1SECOND
        DYNAMIC-MEMORY-STRESS-LARGE-CHUNK
        DYNAMIC-MEMORY-SAVE-RESTORE
        DYNAMIC-MEMORY-HIGH-PRIORITY
        DYNAMIC-MEMORY-START-HIGH-COMPETE
        HOT-REMOVE
        STARTUP-LOW-COMPETE
        CLEAN-SHUTDOWN
        DYNAMIC-MEMORY-DEMAND-PRESSURE
        DYNAMIC-MEMORY-MAX-MEMORY-HONORED
        DYNAMIC-MEMORY-MIN-MEMORY-HONORED
        DYNAMIC-MEMORY-TOP-LOAD-AVERAGE
        DYNAMIC-MEMORY-HOT-REMOVE-THEN-PRESSURE
        DYNAMIC-MEMORY-HOT-ADD-EAT-MEM-SMP
        DYNAMIC-MEMORY-HOT-ADD-EAT-MEM-UP
        STOR-VSS-BACKUPRESTORE-ISO-NONETWORK
        STOR-VSS-BACKUPRESTORE-MULTIFS-VHDX
        STOR-VSS-3CHAIN-VHD-BACKUP
        STOR-VSS-BACKUP-PRESTORE-STATE-PAUSED
        STOR-VSS-BACKUP-RESTORE-MOUNT-MULTI-PATHS
        STOR-VSS-BACKUP-RESTORE-MOUNT-SQUASHFS        
        STOR-VSS-BACKUP-RESTORE-DISKSTRESS
        STOR-VSS-BACKUP-DISABLE-ENABLE-VSS
        STOR-VSS-BACKUP-RESTORE-FAIL

**Comment by asofron** [comment]
I`m already working on fixing PRODUCTION-CHECKPOINT, DYNAMIC_MEMORY, AND RUNTIME_MEMORY

**Comment by ader1990** [comment]
> Per @ader1990 , we need fix them in test cases.

at this moment, it is easier to rename them back to ResultPass/ResultFail, as the new namings have not been used for other tests.

**Comment by asofron** [comment]
Test cases should not fail anymore but output like : [INFO ] Test case script result does not match known ones: True False True PASS still need to be fixed ( working on it )

**Comment by iamshital** [comment]
@asofron , Can you just check the status in last item of returned array?
`$TestResult = $ReturnedResult[-1]`

**Comment by asofron** [comment]
@iamshital  Fixing the escaped output will make it easier to fix the test cases and debug them , also this way we will not encounter this issue the future

**Comment by ader1990** [comment]
> @asofron , Can you just check the status in last item of returned array?
> `$TestResult = $ReturnedResult[-1]`

this is already being done in lisav2 framework, but I would like to remove that code that checks for abort|fail in the testcase output, which is very frail and prone to errors. If the test case runs a command that outputs to the console a string like "pass" or "fail", lisav2 can give false positives/negatives.

**Comment by lizzha** [comment]
The issue seems to have been fixed, what else need to be done regarding this issue? If not, we can close it.
