### ISSUE TITLE
lisav2 is duplicating the backing vhd file on hyperv

### ISSUE THREAD

**Issue by ader1990** [LIS/LISAv2#767]
Due to PR https://github.com/LIS/LISAv2/pull/694/files#diff-accdabd42ae9ba14f2b523565689e2ceR339, there is a duplication of VHDs if LISAv2 is run using HyperV platform and the OsVhd path is a local one.

How to fix the issue:
Do not cache the VHD if lisav2 is creating vms on the same server where it runs.

**Comment by iamshital** [comment]
I got this. I just need to skip the copy VHD if `-OsVHD <LocalVHD>` and `LISAv2 executer == Server under test`. Otherwise, I still need to copy the VHD. @ader1990 Please Confirm.

**Comment by juhlee-microsoft** [comment]
Close because we only hold P0
