### ISSUE TITLE
LISAv2: Distro should be detected as soon as VM is created

### ISSUE THREAD

**Issue by iamshital** [LIS/LISAv2#787]
... and detected distro should be available for further operations.
This will enable some functions to do distro specific operations.
E.g. `Register-RhelSubscription`. This way we can skip unnecessary steps.

**Comment by iamshital** [comment]
@juhlee-microsoft  This is falls under "improvement" category and not blocking anything now. Hence moved to March - 2019.

**Comment by LiliDeng** [comment]
#813
