### ISSUE TITLE
Replace .\tools\plink.exe with Run-LinuxCmd

### ISSUE THREAD

**Issue by iamshital** [LIS/LISAv2#788]
As of now, I'm seeing 30+ occurrences of direct use of `.\tools\plink.exe`.
In order to maintain a continuity throughout the framework, we need to use `Run-LinuxCmd`.

![image](https://user-images.githubusercontent.com/7985635/53168886-8ede3200-3590-11e9-9fd1-456f53cab731.png)

**Comment by juhlee-microsoft** [comment]
Close non-P0 issues
