### ISSUE TITLE
Block the run-time in install-package'

### ISSUE THREAD

**Issue by juhlee-microsoft** [LIS/LISAv2#792]
SetupRDMA.sh line 62 show below line. 'install-package' pops up question during run-time below. This is not supported image but there is customer who wants SLES12 sp3 standard image with package installation. Need to remove this question 'Continue'.

<command in the script>
`install_package "kernel-devel-3.10.0-862.9.1.el7.x86_64 python-devel valgrind-devel redhat-rpm-config rpm-build gcc-gfortran libdb-devel gcc-c++ glibc-devel zlib-devel numactl-devel libmnl-devel binutils-devel iptables-devel libstdc++-devel libselinux-devel gcc elfutils-devel libtool libnl3-devel git java libstdc++.i686 dapl python-setuptools gtk2 atk cairo tcl tk createrepo libibverbs-devel libibmad-devel byacc.x86_64 kernel-devel-3.10.0-862.11.6.el7.x86_64"
`

<error log in SLES 12 SP3 standard image>

> zypper_install expect glibc-32bit glibc-devel libgcc_s1 libgcc_s1-32bit make gcc gcc-c++ gcc-fortran rdma-core libibverbs-devel librdmacm1 libibverbs-utils bison flex: Success
> Fri Feb 22 00:40:46 2019 : zypper_install expect glibc-32bit glibc-devel libgcc_s1 libgcc_s1-32bit make gcc gcc-c++ gcc-fortran rdma-core libibverbs-devel librdmacm1 libibverbs-utils bison flex: Success
> spawn zypper in libibmad-devel
> Refreshing service 'SMT-http_smt-azure_susecloud_net'.
> Refreshing service 'cloud_update'.
> Loading repository data...
> Reading installed packages...
> Resolving package dependencies...
> 
> The following 2 NEW packages are going to be installed:
>   libibmad-devel libibmad5
> 
> The following package has no support information from it's vendor:
>   libibmad-devel
> 
> 2 new packages to install.
> Overall download size: 52.9 KiB. Already cached: 0 B. After the operation, additional 176.7 KiB will be used.
> Continue? [y/n/...? shows all options] (y):
>

**Comment by LiliDeng** [comment]
@juhlee-microsoft I install a new fresh VM (SUSE Linux Enterprise Server 12 SP3), copy utils.sh, run install_package "expect glibc-32bit glibc-devel libgcc_s1 libgcc_s1-32bit make gcc gcc-c++ gcc-fortran rdma-core libibverbs-devel librdmacm1 libibverbs-utils bison flex", didn't hit this issue.

Could you please share the command line for running case?

**Comment by juhlee-microsoft** [comment]
This is from Pxxx jenkins. You can find below values from the job log.
job 741: SUSE SLES 12-SP3 2018.09.04
Or, you can start Microsoft-Launch-Start > Build with Parameters -> SUSE / SLES / 12-SP3 / <last value>

**Comment by LiliDeng** [comment]
Break in below line, remove bold lines or using non-interactive, testing using update code now
             expect -c "spawn zypper in libibmad-devel
                 **expect -timeout -1 \"Choose from\"
                 send \"2\r\"**
                 expect -timeout -1 \"Continue\"
                 send \"y\r\"
                 interact
             "
zypper --non-interactive in  libibmad-devel

**Comment by LiliDeng** [comment]
First solution, need do regression testing for other sles version.

https://github.com/LiliDeng/LISAv2/commit/180e664b91d55eb0d9423e17756e588147cd7259
···

[LISAv2 Test Results Summary]
Test Run On           : 02/22/2019 11:27:48
ARM Image Under Test  : SUSE : SLES : 12-SP3 : 2018.09.04
Total Test Cases      : 1 (1 Passed, 0 Failed, 0 Aborted, 0 Skipped)
Total Time (dd:hh:mm) : 0:0:41

   ID TestCaseName                                                                TestResult TestDuration(in minutes) 
---------------------------------------------------------------------------------------------------------------------
    1 INFINIBAND-OPEN-MPI-2VM                                                           PASS                27.82 
	InfiniBand-Verification-1-FirstBoot : eth0 IP : PASS 
	InfiniBand-Verification-1-FirstBoot : IBV_PINGPONG : PASS 
	InfiniBand-Verification-1-FirstBoot : PingPong Intranode : PASS 
	InfiniBand-Verification-1-FirstBoot : IMB-MPI1 : PASS 
	InfiniBand-Verification-1-FirstBoot : IMB-RMA : PASS 
	InfiniBand-Verification-1-FirstBoot : IMB-NBC : PASS 
	InfiniBand-Verification-2-Reboot : eth0 IP : PASS 
	InfiniBand-Verification-2-Reboot : IBV_PINGPONG : PASS 
	InfiniBand-Verification-2-Reboot : PingPong Intranode : PASS 
	InfiniBand-Verification-2-Reboot : IMB-MPI1 : PASS 
	InfiniBand-Verification-2-Reboot : IMB-RMA : PASS 
	InfiniBand-Verification-2-Reboot : IMB-NBC : PASS 
 
···

**Comment by LiliDeng** [comment]
Second solution, https://github.com/LiliDeng/LISAv2/commit/a70ac73f88157692e2ba077ed25be3159948e49c
during testing, less possibility to bring in regression issue

**Comment by juhlee-microsoft** [comment]
@LiliDeng Please limit your regression in SLES 12 SP4 and SLES 12 SP3. If you can make it in SLES 15, it would be better. No other images.
