### ISSUE TITLE
CustomLIS parameter should only work for Redhat/CentOS/Oracle-Redhat-kernel

### ISSUE THREAD

**Issue by juhlee-microsoft** [LIS/LISAv2#793]
### Command
PS C:\Users\juhlee\Source\Repos\LISAv2> .\Run-LisaV2.ps1 -TestPlatform "Azure" -TestLocation "<xxx>" -ARMImageName "<xx ub 18004 xx>" -RGIdentifier "<xxx>" -TestNames "VERIFY-SRIOV-LSPCI" -XMLSecretFile <secret file path> -CustomLIS lisnext

### Test result

> [LISAv2 Test Results Summary]
> Test Run On           : 02/22/2019 00:31:03
> ARM Image Under Test  : xxxxx
> Total Test Cases      : 1 (0 Passed, 0 Failed, 1 Aborted, 0 Skipped)
> Total Time (dd:hh:mm) : 0:0:5
> 
>    ID TestCaseName                                                                TestResult TestDuration(in minutes)
> ---------------------------------------------------------------------------------------------------------------------
>     1 VERIFY-SRIOV-LSPCI                                                             Aborted                    0
> 
> 
> Logs can be found at C:\LISAv2\xxx\TestResults\2019-21-02-16-30-59-5731
> 
> 
> 02/22/2019 00:36:37 : [INFO ] Current Git Branch:  master
> 02/22/2019 00:36:37 : [INFO ] Current Git Commit ID: 95c4d36226980dd2f7989722ec7433a672d78747
> 02/22/2019 00:36:37 : [INFO ] Creating 'C:\LISAv2\xxx\Azure-xxx-TestLogs.zip' from 'C:\LISAv2\xxx\TestResults\2019-21-02-16-30-59-5731'
> 02/22/2019 00:36:37 : [INFO ] C:\LISAv2\xxx\Azure-xxx-TestLogs.zip created successfully.
> 02/22/2019 00:36:37 : [INFO ] Analyzing results..
> 02/22/2019 00:36:37 : [INFO ] Copying all files back to original working directory: C:\Users\juhlee\Source\Repos\LISAv2.
> 02/22/2019 00:36:42 : [INFO ] Setting workspace back to original location: C:\Users\juhlee\Source\Repos\LISAv2
> 02/22/2019 00:36:42 : [INFO ] LISAv2 exit code: 1
> 

In the middle of run-time, it shows below.

02/22/2019 01:02:00 : [INFO ] .\tools\plink.exe -t -pw ****** -P 22 root@xx.xx.xx.xx "cp -ar /home/lisa/*.sh ."
02/22/2019 01:02:02 : [ERROR] Looking up host "xx.xx.xx.xx"    + CategoryInfo          : NotSpecified: (Looking up host "xx.xx.xx.xx":String) [], RemoteException    + FullyQualifiedErrorId : NativeCommandError    + PSComputerName        : localhost Connecting to xx.xx.xx.xx port 22Server version: SSH-2.0-OpenSSH_7.6p1 Ubuntu-4ubuntu0.2Using SSH protocol version 2We claim v
ersion: SSH-2.0-PuTTY_Release_0.63Server supports delayed compression; will try this laterUsing Diffie-Hellman with standard group "group14"Doing Diffie-Hellman key exchange with hash SHA-1
02/22/2019 01:02:02 : [ERROR] Host key fingerprint is:ssh-rsa 2048 1a:84:5b:c5:3f:09:a0:62:54:eb:98:e7:53:89:d2:acInitialised AES-256 SDCTR client->server encryptionInitialised HMAC-SHA-256 client->server MAC algorithmInitialised AES-256 SDCTR server->client encryptionInitialised HMAC-SHA-256 server->client MAC algorithm
02/22/2019 01:02:02 : [ERROR] Using username "root".Sent passwordAccess grantedInitiating key re-exchange (enabling delayed compression)Opening session as main channel
02/22/2019 01:02:03 : [ERROR] Using Diffie-Hellman with standard group "group14"Doing Diffie-Hellman key exchange with hash SHA-1
02/22/2019 01:02:03 : [ERROR] Initialised AES-256 SDCTR client->server encryptionInitialised HMAC-SHA-256 client->server MAC algorithmInitialised zlib (RFC1950) compressionInitialised AES-256 SDCTR server->client encryptionInitialised HMAC-SHA-256 server->client MAC algorithmInitialised zlib (RFC1950) decompression
02/22/2019 01:02:03 : [ERROR] Opened main channel
02/22/2019 01:02:03 : [ERROR] Allocated pty (ospeed 38400bps, ispeed 38400bps)Started a shell/commandSent EOF message
02/22/2019 01:02:03 : [ERROR] Server sent command exit status 0Disconnected: All channels closed
02/22/2019 01:02:03 : [ERROR] Linux machine returned exit code : 127
02/22/2019 01:02:03 : [ERROR] Failed to execute : cp -ar /home/lisa/*.sh .. Retrying...
02/22/2019 01:02:06 : [INFO ] cp -ar /home/lisa/*.sh . executed successfully in 5.51 seconds.

**Comment by LiliDeng** [comment]
This is not the exact error for case fail. since the last line shows executed successfully
02/22/2019 01:02:06 : [INFO ] cp -ar /home/lisa/*.sh . executed successfully in 5.51 seconds.

**Comment by juhlee-microsoft** [comment]
I am confirmed CustomLIS installation is only allowed for CentOS, RHEL and Oracle images. Please add filtering in the beginning of execution.

**Comment by iamshital** [comment]
@juhlee-microsoft I'm aware about this error and cause as well. Just need a minor fix. But this is not related to LIS installation failure and this not breaking LISAv2. Please change the subject and make this issue P2 / P3. Also, you tried ubuntu, which is not supported.

**Comment by juhlee-microsoft** [comment]
Need to filter for CustomLIS parameter. This should be only available for above distros
