### ISSUE TITLE
Perf-Network tests: Add support for OracleLinux

### ISSUE THREAD

**Issue by LiliDeng** [LIS/LISAv2#794]
|   | Ubuntu 18.04 | Debian 9 | RedHat 75 | CentOS 75 | OracleLinux | SLES 15 | CoreOS | ClearOS-basic
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
5 | PERF-NETWORK-TCP-THROUGHPUT-MULTICONNECTION-NTTTCP-Synthetic | PASS | PASS | PASS | PASS | Aborted | PASS | PASS | PASS
6 | PERF-NETWORK-TCP-THROUGHPUT-MULTICONNECTION-NTTTCP-SRIOV | PASS | PASS | PASS | PASS | Aborted | PASS | PASS | Aborted
7 | PERF-NETWORK-UDP-1K-THROUGHPUT-MULTICONNECTION-NTTTCP-Synthetic | PASS | PASS | PASS | PASS | Aborted | PASS | PASS | PASS
8 | PERF-NETWORK-UDP-1K-THROUGHPUT-MULTICONNECTION-NTTTCP-SRIOV | PASS | PASS | PASS | PASS | Aborted | PASS | PASS | Aborted
9 | PERF-NETWORK-TCP-LATENCY-MULTICONNECTION-Synthetic | PASS | PASS | PASS | PASS | Aborted | PASS | PASS | PASS
10 | PERF-NETWORK-TCP-LATENCY-MULTICONNECTION-SRIOV | PASS | PASS | PASS | PASS | Aborted | PASS | PASS | Aborted
11 | PERF-NETWORK-UDP-THROUGHPUT-MULTICONNECTION-Synthetic | PASS | PASS | PASS | PASS | Aborted | PASS | PASS | PASS
12 | PERF-NETWORK-UDP-THROUGHPUT-MULTICONNECTION-SRIOV | PASS | PASS | PASS | PASS | Aborted | PASS | PASS | Aborted

**Comment by juhlee-microsoft** [comment]
Missing information, why doesn't it work in Oracle Linux?

**Comment by LiliDeng** [comment]
For example, no entry for oraclelinux distro when install ntttcp.
https://github.com/LIS/LISAv2/blob/master/Testscripts/Linux/utils.sh#L2599
