### ISSUE TITLE
SRIOV-VERIFY-VF-MAX-CONNECTION-MAX-VCPU: Add grub param before test

### ISSUE THREAD

**Issue by chvalean** [LIS/LISAv2#818]
Add **hv_storvsc.storvsc_ringbuffer_size=131072** flag to grub for this test in order to avoid a known issue.
Mark this as a work-around for Azure until it will be fixed in a couple of months.

**Comment by simonxiaoss** [comment]
we should fail this test case because it is related to a real issue here.
