### ISSUE TITLE
Hyper-V: Failed to update configuration files. -XMLSecuretFile [FilePath] is not provided. 

### ISSUE THREAD

**Issue by lixuemin2016** [LIS/LISAv2#825]
Two possible issues here:

1. When run test for platform "Hyper-V", if do not provides -XMLSecuretFile, will get the error "Failed to update configuration files. -XMLSecuretFile [FilePath]' is not provided. ", this parameter -XMLSecuretFile should be optional for Hyper-v? Currently will output the red error log even it does not block test.

2. Cannot find xmlSecretFile template in the XML folder.  After check from script, it should include following elements. Do we need to put one secret xml template in the test framework? 
                     $hyperVConfig.TestCredentials.LinuxUsername = $secrets.linuxTestUsername
			$hyperVConfig.TestCredentials.LinuxPassword = $secrets.linuxTestPassword
			$hyperVConfig.ResultsDatabase.server = $secrets.DatabaseServer
			$hyperVConfig.ResultsDatabase.user = $secrets.DatabaseUser
			$hyperVConfig.ResultsDatabase.password = $secrets.DatabasePassword
                     $hyperVConfig.ResultsDatabase.dbname = $secrets.DatabaseName

Thank you so much.

**Comment by juhlee-microsoft** [comment]
Close non-P0 issues
