### ISSUE TITLE
LISAv2 : Telemetry data upload to DB is not working.

### ISSUE THREAD

**Issue by iamshital** [LIS/LISAv2#834]
In database.psm1, there are two definitions of Upload-TestResultToDatabase(). 
Need to combine these into one.

**Comment by LiliDeng** [comment]
it can enter into correct one if provide the proper parameter?

**Comment by iamshital** [comment]
@lizzha , As far as I know, function overloading is not supported in Powershell. The last definition will override previous definition.
And in #804 , You created the same function with different parameter. Looks like, it happened by mistake.
Can you confirm?

**Comment by iamshital** [comment]
> it can enter into correct one if provide the proper parameter?

It is not happening. I checked that, it is always entering into the last definition of 
Upload-TestResultToDatabase()
