### ISSUE TITLE
Refactor Powershell scripts

### ISSUE THREAD

**Issue by lizzha** [LIS/LISAv2#94]
From comments in PR #85, #78 
follow best practices in a best effort manner:: https://github.com/PoshCode/PowerShellPracticeAndStyle/blob/master/Style-Guide/Introduction.md or a shorter version like: https://github.com/ader1990/PowerShell-Guidelines

1. use 4 spaces as indent
2. function name in Verb-Entity format, variable name using camelCase
3. put as much code in functions as you can
4. write used global variables in comment
To be added...

**Comment by juhlee-microsoft** [comment]
This is the second duplicated record for our code refactoring.  #19 & #87 

@lizzha is this the same purpose like other two?

**Comment by juhlee-microsoft** [comment]
Merged to #19
