### ISSUE TITLE
Relocate binary files to Azure blob

### ISSUE THREAD

**Issue by juhlee-microsoft** [LIS/LISAv2#99]
GitHub warns out that we checked in 4x binary files to Tools folder. I uploaded 4 files to Azure Blob and change the code for accessing to Azure blob files.

Azure Blob: partnerpipelineshare -> binarytools

https://partnerpipelineshare.file.core.windows.net/binarytools

**Comment by ader1990** [comment]
https://github.com/LIS/LISAv2/tree/master/Tools all the binaries from this folder should either be removed or their licenses added.

**Comment by juhlee-microsoft** [comment]
@ader1990 you are right. I have a few warning msg from GitHub and plan to remove them. Instead, will use Azure blob. I think we should modify scripts for new blob URL. Is it something you can do?

**Comment by juhlee-microsoft** [comment]
PR #110
